function segFlag()
% This code is to generate the flag for each sample using the manually
% pick-up segments of clipped parts of a seismic waveform.
%
% Input:  1). "flagZ.txt", which is the manually pick-up segments of clipped parts of a seismic 
%             waveform, generated by "pickupPointsManually".  
%         2). 'MAJO10Z.txt', which is the seismic data, generated by "pickupPointsManually"
%
%Output:  1). 'flagAllZ.txt', which is the flag for each sample, according
%             to the the manually pick-up segments
%         2). 'thZ.txt',which is the threhold for each sample. These two
%             output files would be used during the waveform restoration by
%             "waveformRecoveryFlag.m"
%
% Last modified by Jinhai Zhang, Dec 26, 2016
%
% This code can be used for noncommercial purposes only. For commercial use, please contact Prof. Jinhai Zhang, zjh@mail.iggcas.ac.cn
%
% Please cite this code in terms of the related technical papers:
%
% Zhang, J. H. et al., 2016, Restoration of clipped seismic waveforms using projection onto convex sets method, Scientific Reports,6:39056, doi: 10.1038/srep39056
% Wang, S. Q. & Zhang, J. H. Fast image inpainting using exponential-threshold POCS plus conjugate gradient. Imaging. Sci. J. 62, 161¨C170 (2014).
%
% By using this software, you are agreeing to the terms detailed below.

% BEGIN TERMS OF USE LICENSE
%
% This SOFTWARE is maintained by the Seismology Group at the Institute
% of Geology and Geophysics, Chinese Academy of Sciences, Beijing,
% China.  The copyright and ownership is held by its 'AUTHOR'. 
% Please contact us via email at: zjh@mail.iggcas.ac.cn
%
% The term 'SOFTWARE' refers to the Matlab source code, translations to
% any other computer language, or object code
%
% Terms of use of this SOFTWARE
%
% 1) This SOFTWARE may be used by any individual or corporation for noncommercial purposes
%    with the exception of re-selling or re-distributing the SOFTWARE.
%
% 2) The AUTHORS should be acknowledged in any resulting publications or
%    presentations
%
% 3) This SOFTWARE is provided "as is" with no warranty of any kind
%    either expressed or implied. We make no warranties or representation
%    as to its accuracy, completeness, or fitness for any purpose. We
%    are under no obligation to provide support of any kind for this SOFTWARE.
%
% 4) New versions will be made available after leaving your email to zjh@mail.iggcas.ac.cn
%
% 5) Use this SOFTWARE at your own risk.
%
% END TERMS OF USE LICENSE

aa=importdata('flagZ.txt');%import "flagZ.txt", which is generated by "pickupPointsManually"
a=reshape(aa,2,size(aa,1)/2);%rearrange the begining and ending index for each segment. a(1):begining; a(2): ending
seis=importdata('MAJO10Z.txt');%input the seismic data, which is generated by "pickupPointsManually"
nt=size(seis,1);
ff=zeros(nt);%initialize the flag as "0" (i.e. not clipped)
th=seis;
for ii=1:size(aa,1)/2
    b=floor(a(1,ii));%begining index
    c=floor(a(2,ii));%ending index
    ff(b:c)=1; %mark the clipped area as "1" (i.e. clipped)
    
    %save the waveform amplitude as the threhold for the clipped area (i.e. the marked segment)
    if seis(b)>0 %for positive amplitude
        th(b:c)=0.5*(th(b)+th(c));%the threshold is the amplitude average of the beginning and the ending positions
    end
    if seis(b)<0 %for nagtive amplitude
        th(b:c)=0.5*(th(b)+th(c));%the threshold is the amplitude average of the beginning and the ending positions
    end
end
fid = fopen('flagAllZ.txt','wt');%save flag into "flagAllZ.txt"
for ii=1:size(ff,1)
    fprintf(fid,'%f \n',ff(ii));
end
fclose(fid);

fid = fopen('thZ.txt','wt');%save threhold into "thZ.txt"
for ii=1:size(ff,1)
    fprintf(fid,'%f \n',th(ii));
end
fclose(fid);

flag=importdata('flagAllZ.txt');%input "flagAllZ.txt"
figure(1)
plot(seis,'r.-');hold on;%plot original waveform as red dots
plot(seis(1:nt).*flag(1:nt),'bo');hold on;%plot clipped samples as blue circles
plot(th(1:nt).*flag(1:nt),'g*');hold on;%plot threshold as green asterisks
xlim([1  60000]);